library(ISLR)
fix(Auto) #edit on Auto
dim(Auto)
Auto=na.omit(Auto)
dim(Auto)
names(Auto)
plot(Auto$cylinders , Auto$mpg )
attach(Auto)
plot(cylinders , mpg)
cylinders=as.factor(cylinders)
plot(cylinders,mpg)
plot(cylinders,mpg,col="red")
plot(cylinders,mpg,col="red",varwidth=T)
plot(cylinders,mpg,col="red",varwidth=T,horizental=T)
plot(cylinders , mpg , col ="red", varwidth =T, xlab="cylinders ",
     ylab="MPG")
hist(mpg ,col =2)
hist(mpg ,col =2,breaks=15)
pairs(Auto)
pairs(~mpg + displacement + horsepower + weight +
         acceleration , Auto)
plot(horsepower ,mpg)
identify (horsepower ,mpg ,name)
summary(Auto)
summary(year)
